"""Create ai_models table.

Revision ID: 3b7cb2841912
Revises: cad30a82c53f
Create Date: 2024-08-07 14:45:08.539386+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "3b7cb2841912"
down_revision: Union[str, None] = "cad30a82c53f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(["type_id"], ["ai_types.id"], name=op.f("fk_ai_models_type_id_ai_types")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_models")),
        sa.UniqueConstraint("name", name=op.f("uq_ai_models_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_models")
    # ### end Alembic commands ###
