"""Add balance to users.

Revision ID: d5c642daaf2c
Revises: ba048aae0146
Create Date: 2024-08-07 14:31:02.979774+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "d5c642daaf2c"
down_revision: Union[str, None] = "ba048aae0146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("balance", sa.Numeric(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
